# doctrine.dbal:
#   default_connection: default
#   connections:
#     default:
#       driver: PDOPgSql  # PDOSqlite, PDOMySql, PDOMsSql, PDOOracle, PDOPgSql, OCI8
#       dbname: cartapatate_hurepoix
#       user: cartapatate
#       password: pFWxLvY58
#       a:
#         a1: sde
#         a2: zedfzre

# doctrine.orm:
#   default_entity_manager: default
#   metadata_driver: annotation           # xml, yml, annotation
#   cache_driver: apc                     # array, apc, memcache, xcache
#   entity_managers:
#     default:
#       connection: default

doctrine_mongodb:
  #server: mongodb://localhost:27017
  connections:
    default:
      server: mongodb://localhost:27017
  default_database: "%kernel.name%_dev"
  #default_document_manager: default
  # auto_generate_proxy_classes: true
  # auto_generate_hydrator_classes: true
  # metadata_cache_driver: array
  # mappings:
  #   PloomapBundle: ~
  #   ZigBundle: ~
  #   PgLinkBundle: ~
  document_managers:
    default:
      connection: default
      metadata_cache_driver: array
      mappings:
        StofDoctrineExtensionsBundle: ~
        GeonefPloomapBundle: ~
        GeonefZigBundle: ~
        GeonefPgLinkBundle: ~

stof_doctrine_extensions:
    default_locale: zz
    translation_fallback: false
    # orm:
    #     #default: ~
    #     translatable: false
    #     timestampable: false
    #     sluggable: false
    #     tree: false
    #     loggable: false
    mongodb:
      default:
        translatable: true
        timestampable: false
        sluggable: false
        tree: false
        loggable: false
        sortable: false
    # class:
    #   translatable: Stof\DoctrineExtensionsBundle\Listener\TranslationListener
    #   timestampable: Gedmo\Timestampable\TimestampableListener
    #   sluggable: Gedmo\Sluggable\SluggableListener
    #   tree: Gedmo\Tree\TreeListener
    #   loggable: Stof\DoctrineExtensionsBundle\Listener\LoggableListener


