#!/usr/bin/env php
<?php

require_once __DIR__.'/Kernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$env = trim(file_get_contents(__DIR__.'/ENV'));
$kernel = new Kernel($env, true);

$application = new Application($kernel);
$application->run();
