
geonef_zig:

  static_cache:

    enabled: true

    routes:

      home_i18n:
        cachePattern: "{_route}/{_locale}.html"
        dependencies:
          - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [title], filter: {locale: _locale} }
          - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [published, position] }
          - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [title], filter: {locale: _locale} }
          - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [published, position] }

      aire_collection_visu_i18n:
        cachePattern: "{_route}/{_locale}/{id}.html"
        dependencies:
          - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [title], filter: {locale: _locale} }
          - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [published, position] }
          - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [title], filter: {locale: _locale} }
          - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [published, position] }
          - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [comment], filter: {uuid: id, locale: _locale}}
        clearingEvents:
          - { event: model.geonefPloomap.map.onMapChange, filter: {mapCollection: id}}

      geonef_ploomap_map_svg_i18n:
        cachePattern: "{_route}/{_locale}/{id}.svg"
        clearingEvents:
          - { event: model.geonefPloomap.map.onMapChange, filter: {uuid: id}}
          - { event: model.geonefPloomap.map.onSvgTemplateChange, filter: {uuid: id}}

      geonef_ploomap_map_csvfeatures_i18n:
        cachePattern: "{_route}/{_locale}/{id}.csv"
        clearingEvents:
          - { event: model.geonefPloomap.map.onMapChange, filter: {uuid: id}}

      admin_i18n:
        cachePattern: "{_route}/{_locale}.html"

    # routes:

    #   home_i18n:
    #     cachePattern: "{_route}/{_locale}.html"
    #     dependencies:
    #       - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [title], filter: {locale: _locale} }
    #       - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [published, position] }
    #       - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [title], filter: {locale: _locale} }
    #       - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [published, position] }

    #   aire_collection_visu_i18n:
    #     cachePattern: "{_route}/{_locale}/{id}.html"
    #     dependencies:
    #       - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [title], filter: {locale: _locale} }
    #       - { class: Geonef\PloomapBundle\Document\MapCategory, properties: [published, position] }
    #       - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [title], filter: {locale: _locale} }
    #       - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [published, position] }
    #       - { class: Geonef\PloomapBundle\Document\MapCollection, properties: [comment], filter: {uuid: id, locale: _locale}}
    #       - { class: Geonef\PloomapBundle\Document\Map, properties: [*], filter: {mapCollection: id}}

    #   geonef_ploomap_map_svg_i18n:
    #     cachePattern: "{_route}/{_locale}/{id}.svg"
    #     dependencies:
    #       - { class: Geonef\PloomapBundle\Document\Map, filter: {uuid: id} }

    #   geonef_ploomap_map_csvfeatures_i18n:
    #     cachePattern: "{_route}/{_locale}/{id}.csv"
    #     dependencies:
    #       - { class: Geonef\PloomapBundle\Document\Map, filter: {uuid: id} }

    #   admin_i18n:
    #     cachePattern: "{_route}/{_locale}.html"
