imports:
  #- { resource: security.yml }
  - { resource: doctrine.yml }
  - { resource: zig.install.yml }
  - { resource: pglink.yml }
  - { resource: parameters.xml }

framework:
  # http://symfony.com/doc/current/reference/configuration/framework.html
  #name: catapatate
  secret: d3c5eb72-98cd-4db9-bfec-9395a65bc94a
  charset: UTF-8
  csrf_protection:
     enabled: true
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  validation: { enabled: true }
  templating:    { engines: ['twig'] }
  session:
    default_locale: en
    auto_start:     true
  translator:
    enabled: true
    fallback: fr

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

sensio_framework_extra: ~

funkiton_injector: ~

# Assetic Configuration
# assetic:
#     debug:          %kernel.debug%
#     use_controller: false
#     filters:
#         cssrewrite: ~
#         # closure:
#         #     jar: %kernel.root_dir%/java/compiler.jar
#         # yui_css:
#         #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar


#zig: ~

# swiftmailer: ~
    # transport: %mailer_transport%
    # host:      %mailer_host%
    # username:  %mailer_user%
    # password:  %mailer_password%

