#
# Routage
#
# http://symfony.com/doc/current/book/routing.html
#

zig:
  resource: "@GeonefZigBundle/Resources/config/routing.yml"
ploomap:
  resource: "@GeonefPloomapBundle/Resources/config/routing.yml"

admin:
  pattern: /admin
  defaults:
     _controller: "GeonefZigBundle:ViewClass:render"
     path: "views.admin"
admin_i18n:
  pattern: /admin/{_locale}
  defaults:
     _controller: "GeonefZigBundle:ViewClass:render"
     path: "views.admin"

home:
  pattern: /
  defaults: { _controller: "RiateAireBundle:Home:home" }
home_i18n:
  pattern: /{_locale}
  defaults: { _controller: "RiateAireBundle:Home:home" }

aire_controllers:
  resource: "@RiateAireBundle/Controller"
  prefix:   /
  type:     annotation
