#catapatate:
#  resource: CatapatateBundle/Resources/config/routing.yml
zig:
  resource: "@GeonefZigBundle/Resources/config/routing.yml"
ploomap:
  resource: "@GeonefPloomapBundle/Resources/config/routing.yml"

homepage:
  pattern: /
  defaults:
    _controller: "GeonefZigBundle:ViewClass:render"
    path: "views.workspace"

admin:
  pattern: /admin
  defaults:
     _controller: "GeonefZigBundle:ViewClass:render"
     path: "views.admin"

