#catapatate:
#  resource: CatapatateBundle/Resources/config/routing.yml
zig:
  resource: "@GeonefZigBundle/Resources/config/routing.yml"
ploomap:
  resource: "@GeonefPloomapBundle/Resources/config/routing.yml"

homepage:
  pattern: /
  defaults:
    _controller: "GeonefZigBundle:ViewClass:render"
    path: "views.workspace"

admin:
  pattern: /admin
  defaults:
     _controller: "GeonefZigBundle:ViewClass:render"
     path: "views.admin"

collection:
  pattern: /collection/{id}
  defaults: { _controller: "GeonefAireBundle:Collection:visu" }

csvFeatures:
  pattern: /map/{id}/csvFeatures
  defaults: { _controller: "GeonefPloomapBundle:Map:csvFeatures" }

svg:
  pattern: /map/{id}/svg
  defaults: { _controller: "GeonefPloomapBundle:Map:svg" }

print:
  pattern: /map/{id}/print
  defaults: { _controller: "GeonefAireBundle:Map:print" }

