geonef_zig:
  app:
    public_dir: %kernel.cache_dir%/public
    lib_dir_path: %kernel.cache_dir%/public/lib
    lib_web_path: /lib
    clients:
      aire_visu:
        copyright: blablabla
        modules:
          - package.collection
          - aire.start.collection
        css:
          - { module: aire, path: style/visu.css }

    modulePaths:
      geonef: %kernel.cache_dir%/public/lib
      aire: %kernel.cache_dir%/public/lib
      #geonef: %kernel.root_dir%/../vendor/ploomap-client/src

    supportedLocales: [ en, fr ]

    localizationModules:
      - dojo
      - dijit
      - geonef.jig
      - geonef.ploomap
      - aire

    publicPaths:
      - ^index\.php$
      # js
      - ^x/workspace\.js$
      - ^x/nls/
      - ^x/dojo/dojo\.js$
      - ^x/collection\.js$
      - ^x/home\.js$
      - ^x/print\.js$
      - ^x/admin\.js$
      - ^x/dojox/gfx/
      # style
      - ^favicon\.ico$
      - ^data/
      - ^image/
      - ^images/
      - ^x/aire/style/visu\.css
      - ^x/aire/style/home\.css
      - ^x/aire/style/admin\.css
      - ^x/aire/style/print\.css
      - ^x/aire/style/icon/
      - ^images/aire/
      - ^x/dojo/resources/blank\.gif$
      - ^x/dijit/themes/tundra/images/
      - ^x/geonef/[^/]+/style/icon/
      - ^x/cartapatate/style/icon/
      - ^lib/cartapatate/style/icon/
      - ^lib/geonef/ploomap/style/marker/
      - ^x/.*/sld/[^/]+\.xml$
      - ^x/dojox/widget/ColorPicker/images/

  install:
    # all paths are relative to the parameter 'kernel.root_dir'
    #manager_class: hehe
    public_dir: %kernel.cache_dir%/public
    public_mappings:
      - { location: '', directory: '../src/Riate/AireBundle/Resources/public' }
      - { location: '', directory: '../vendor/cartapatate' }
      - { location: 'lib', directory: '../vendor/ploomap-client/src' }
      - { location: 'lib', directory: '../vendor/jig/src' }
      - { location: 'images/openlayers', directory: '../vendor/ploomap-client/src/geonef/ploomap/style/openlayers' }
      - { location: 'images/openlayers', directory: '../vendor/openlayers/img' }
      - { location: 'lib/openlayers', directory: '../vendor/openlayers' }
      - { location: 'lib/proj4js', directory: '../vendor/proj4js' }
      - { location: 'lib/dojo', directory: '../vendor/dojo-release/dojo' }
      - { location: 'lib/dijit', directory: '../vendor/dojo-release/dijit' }
      - { location: 'lib/dojox', directory: '../vendor/dojo-release/dojox' }

    shrinksafe:
      buildscripts_dir: ../vendor/dojo-release/util/buildscripts
      release_name: x
      release_dir: %kernel.cache_dir%/public
      build_version: 0.3.0
      profileData:
        prefixes:
          - { ns: dojo, path: %kernel.cache_dir%/public/lib/dojo }
          - { ns: dijit, path: %kernel.cache_dir%/public/lib/dijit }
          - { ns: dojox, path: %kernel.cache_dir%/public/lib/dojox }
          - { ns: cartapatate, path: %kernel.cache_dir%/public/lib/cartapatate }
          - { ns: geonef, path: %kernel.cache_dir%/public/lib/geonef }
          - { ns: aire, path: %kernel.cache_dir%/public/lib/aire }
          - { ns: package, path: %kernel.cache_dir%/public/lib/package }
        layers:
          -
            name: ../admin.js
            resourceName: package.admin
            copyrightFile: '../vendor/cartapatate/lib/cartapatate/copyright.txt'
            dependencies:
              - geonef.jig.start.loadWorkspace
              - package.admin
          -
            name: ../home.js
            resourceName: package.home
            copyrightFile: '../vendor/cartapatate/lib/cartapatate/copyright.txt'
            dependencies:
              - package.home
              - aire.start.home
          -
            name: ../collection.js
            resourceName: package.collection
            copyrightFile: '../vendor/cartapatate/lib/cartapatate/copyright.txt'
            dependencies:
              - package.collection
              - aire.start.collection
          -
            name: ../print.js
            resourceName: package.print
            copyrightFile: '../vendor/cartapatate/lib/cartapatate/copyright.txt'
            dependencies:
              - package.print
              - aire.start.print
