#############################################################
##
##  PHP view of AIRE admin screen
##
#############################################################

class: Geonef\Zig\View\Document\Workspace
title: AIRE - Admin

#############################################################
## HEADER

packageScripts: false
packageStyles: false

scripts:
  require: /lib/require.js
  dojo: /x/dojo/dojo.js
  #openlayers: /js/openlayers/build/OpenLayers.js
  application: /x/admin.js

scriptAffectations:
  window\.workspaceKey: home
  window\.startPackage: package.admin

css:
 #tundra: /x/dijit/themes/tundra/tundra.css
 app: /x/aire/style/admin.css


#############################################################
## BODY

bodyAttributes:
  class: aire tundra

bodyInnerHtml:
  app:
    tag: div
    attributes:
      id: app
    content: ""
  wait:
    tag: div
    attributes:
      id: wait
    content:
      title:
        tag: h1
        content: "Atlas Interactif des Régions Européennes"
      sub:
        tag: div
        content: "Chargement de l'interface d'administration..."

widgets:
  root:
    _class: geonef.jig.layout.RootPane
    state:
      children:
        - tabContainer
        #- mainContainer
      toaster:
        positionDirection: br-left
        #positionDirection: bl-up
  mainContainer:
    _class: geonef.jig.layout.BorderContainer
    state:
      design: sidebar
      children:
        - tabContainer
        #- about
        - adminLibrarySide
      paneSize: 250
  tabContainer:
    _class: geonef.jig.layout.TabContainer
    state:
      children:
        - adminLibrary
      appearTarget: add
      neverEmpty: adminLibrary
  adminLibrary:
    _class: aire.admin.Library
    #state:
    #  appearTarget: bottom
  adminLibrarySide:
    _class: aire.admin.Library
    state:
      gridNbColumns: 1
  about:
    _class: aire.info.About


settings:
  devWidgets:
    - aire.info.About
    - geonef.ploomap.list.OgrDataSource
    - geonef.ploomap.list.OgrLayer
    - geonef.jig.test.Api
    - geonef.ploomap.list.MapCategory
    - geonef.ploomap.list.MapCollection
    - geonef.ploomap.list.Map
  adminWidgets:
    - geonef.ploomap.list.OgrDataSource
    - geonef.ploomap.list.OgrLayer
    - geonef.jig.list.File
    - geonef.ploomap.list.MapCategory
    - geonef.ploomap.list.MapCollection
    - geonef.ploomap.list.Map
    - geonef.ploomap.list.ColorFamily
    - geonef.ploomap.data.list.GdalDataset
    - geonef.jig.data.list.Template
    - { title: "phpPgAdmin", value: "http://phppgadmin.cnrs3.nfrance.com/", icon: '/images/icons/admin_sources.png' }
