title: "Admin-AIRE [DEV]"

# uncomment this to get non-schrinked dojo
#scripts.dojo: /js/dojo/dojo.js
scripts.application: null
scripts.start1: /lib/geonef/jig/start.js
scripts.start2: /lib/geonef/jig/start/loadWorkspace.js
#scripts.openLayers: /js/openlayers/lib/OpenLayers.js

css.app: /lib/aire/style/admin.css

scriptAffectations.window\.devMode: true

bodyAttributes.class: patate tundra dev
